version: '3.8'

services:
  app:
    build: .
    container_name: mimico_app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mimico_db
      SPRING_DATASOURCE_USERNAME: mimico
      SPRING_DATASOURCE_PASSWORD: mimico123
      SPRING_REDIS_HOST: redis

  postgres:
    image: postgres:15
    container_name: mimico_postgres
    restart: always
    environment:
      POSTGRES_USER: mimico
      POSTGRES_PASSWORD: mimico123
      POSTGRES_DB: mimico_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mimico_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
