-- Category: EU_SOU (I am - professions, roles, characters)
INSERT INTO words (category_id, text, difficulty) VALUES
-- Difficulty 1 (Easy) - 15 words
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'fotógrafo', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'mergulhador', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'astronauta', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'pirata', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'ninja', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'vampiro', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'cozinheiro', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'cantor', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'surfista', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'dançarino', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'mágico', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'piloto', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'bombeiro', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'enfermeiro', 1),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'atleta', 1),

-- Difficulty 2 (Medium) - 25 words
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'arquiteto', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'jornalista', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'cientista', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'palestrante', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'escultor', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'sommelier', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'advogado', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'personal trainer', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'DJ', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'estilista', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'youtuber', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'diretor de cinema', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'lutador de boxe', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'skatista profissional', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'acrobata', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'alpinista', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'hacker', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'juiz', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'veterinário', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'tatuador', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'segurança', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'mímico', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'gladiador', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'zumbi', 2),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'faraó', 2),

-- Difficulty 3 (Hard) - 10 words
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'arqueólogo', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'maestro', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'trapezista', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'equilibrista', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'ventriloquo', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'hipnotizador', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'domador de leões', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'escultor de gelo', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'leiloeiro', 3),
((SELECT id FROM word_categories WHERE name = 'eu_sou'), 'pregador', 3);

-- Category: EU_FACO (I do - actions, activities)
INSERT INTO words (category_id, text, difficulty) VALUES
-- Difficulty 1 (Easy) - 15 words
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'acampar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'remar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer churrasco', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'surfar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'andar de skate', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'pescar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fotografar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer caminhada', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'jogar bola', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'nadar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'correr', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'dançar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'cantar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'cozinhar', 1),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'dirigir', 1),

-- Difficulty 2 (Medium) - 25 words
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer yoga', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'meditar', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'esquiar', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'mergulhar', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'escalar montanha', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'trocar pneu', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer malabarismo', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'tocar violão', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer mágica', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'andar de patins', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'montar barraca', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer tatuagem', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'consertar celular', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer reciclagem', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'plantar árvore', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer massagem', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'afinar instrumento', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'acender fogueira', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer pão', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'domar cavalo', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'lustrar sapatos', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'desossar frango', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'empinar pipa', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer discurso', 2),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'resolver cubo mágico', 2),

-- Difficulty 3 (Hard) - 10 words
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer rapel', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'praticar arco e flecha', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer parkour', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'jogar xadrez', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer origami', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'tocar bateria', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer breakdance', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'praticar tai chi chuan', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'fazer slackline', 3),
((SELECT id FROM word_categories WHERE name = 'eu_faco'), 'esculpir', 3);

-- Category: OBJETO (Object - things, items)
INSERT INTO words (category_id, text, difficulty) VALUES
-- Difficulty 1 (Easy) - 15 words
((SELECT id FROM word_categories WHERE name = 'objeto'), 'lanterna', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'trampolim', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'capacete', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'skate', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'bicicleta', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'violão', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'câmera', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'guarda-chuva', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'mochila', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'óculos', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'relógio', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'telefone', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'bola', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'livro', 1),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'chave', 1),

-- Difficulty 2 (Medium) - 25 words
((SELECT id FROM word_categories WHERE name = 'objeto'), 'aspirador de pó', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'liquidificador', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'furadeira', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'binóculos', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'bússola', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'extintor', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'ampulheta', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'microscópio', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'telescópio', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'martelo', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'alicate', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'serra', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'rolo de pintura', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'cadeira de rodas', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'churrasqueira', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'caixa de ferramentas', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'peneira', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'balança', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'termômetro', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'cofre', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'saca-rolhas', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'bomba de pneu', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'nível de pedreiro', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'compasso', 2),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'tripé', 2),

((SELECT id FROM word_categories WHERE name = 'objeto'), 'estetoscópio', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'metrônomo', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'sextante', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'ábaco', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'matraca', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'manivela', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'catapulta', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'carretilha', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'pêndulo', 3),
((SELECT id FROM word_categories WHERE name = 'objeto'), 'bússola náutica', 3);
